[tool.poetry]
name = "yql-x-server"
version = "0.1.0"
description = ""
authors = ["electimon <electimon@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
iso3166 = "^2.1.1"
geopy = "^2.4.1"
jinja2 = "^3.1.4"
cachetools = "^5.4.0"
requests = "^2.32.3"
yfinance = "^0.2.40"
feedparser = "^6.0.11"
fastapi = "^0.111.1"
langcodes = "^3.4.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
